<a href="https://colab.research.google.com/github/kundetigowtham06/ML/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 1

In [2]:
import numpy as np

##1. Perform arithmetic operations on NumPy arrays.


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
#Addition
print(np.add(a,b))
#Subtraction
print(np.subtract(b,a))
#multiplication
print(np.multiply(a,b))
#Divison
print(np.divide(a,b))

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


##2. Write a script to compute the mean and standard deviation of a NumPy array.


In [ ]:
mean=np.mean(a)
standard=np.std(a)
print("Mean",mean)
print("Standard Deviation",standard)

Mean 2.0
Standard Deviation 0.816496580927726


##3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [ ]:
c=np.arange(10,51,5)
print(c)

[10 15 20 25 30 35 40 45 50]


##4. Reshape the array into a 2x4 matrix.


In [ ]:
g=np.array([1,2,3,4,5,6,7,8])
g=g.reshape(2,4)
print(g)

[[1 2 3 4]
 [5 6 7 8]]


##5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):


*    Extract the sub-matrix containing the last two rows and first two columns.

*    Replace all elements greater than 4 with 0.








In [ ]:
#Extract the sub-matrix containing the last two rows and first two columns
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("last two rows and first two colums")
print(arr[1:,0:2])
#Replace all elements greater than 4 with 0
print('------------------')
arr[arr>4]=0
print(arr)


last two rows and first two colums
[[4 5]
 [7 8]]
------------------
[[1 2 3]
 [4 0 0]
 [0 0 0]]


##6. Create two 1D arrays:


*   a = np.array([1, 2, 3])
*   b = np.array([4, 5, 6])
*   Perform element-wise addition, multiplication, and division.




In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a/b)


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 7.Create a random NumPy array of size (4, 4). Compute

*   Mean of each column.
*   Maximum value of the entire array.
*   Sum of all elements.





In [ ]:
ar=np.random.randint(1,21,size=(4,4))
print(np.mean(ar,axis=0))
print(np.max(ar))
print(np.sum(ar))

[13.5   9.25  9.5   5.75]
19
152


## 8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [ ]:
arr=np.array([1,2,3,4])
arr+=10
print(arr*2)

[22 24 26 28]


## 9. Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100

*   Extract the second "layer" (i.e., the second 2D array) in the first dimension.
*   Extract the first two rows and the last three columns from each "layer."
* Replace all elements divisible by 3 with -1.


In [ ]:
arr = np.random.randint(1, 101, size=(3, 4, 5))
print(arr)
print('------------------')
print(arr[1])
print('------------------')
print(arr[:,0:2,-3:])
print('------------------')
arr[arr%3==0]=-1
print(arr)

[[[50 46 69 58 96]
  [72 57 62 66 66]
  [16 55 52 32 82]
  [62 81 54 58 62]]

 [[51 76 18 89  7]
  [66 98 81 59 91]
  [39 73 97 90 27]
  [46 12 30 16 84]]

 [[47 30 93 79 62]
  [40 49 18 26 81]
  [14 39 79 76 96]
  [25 21 53  2 97]]]
------------------
[[51 76 18 89  7]
 [66 98 81 59 91]
 [39 73 97 90 27]
 [46 12 30 16 84]]
------------------
[[[69 58 96]
  [62 66 66]]

 [[18 89  7]
  [81 59 91]]

 [[93 79 62]
  [18 26 81]]]
------------------
[[[50 46 -1 58 -1]
  [-1 -1 62 -1 -1]
  [16 55 52 32 82]
  [62 -1 -1 58 62]]

 [[-1 76 -1 89  7]
  [-1 98 -1 59 91]
  [-1 73 97 -1 -1]
  [46 -1 -1 16 -1]]

 [[47 -1 -1 79 62]
  [40 49 -1 26 -1]
  [14 -1 79 76 -1]
  [25 -1 53  2 97]]]


##  10.Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between  1 and 20.

*    Subtract the mean of each row from its respective elements (row-wise
normalization).
*   Create a new array by squaring all the elements in arr.
*   Find the indices of the top 3 maximum values in the entire array.



In [4]:
a=np.random.randint(1,21,size=(3,3))
print(a)
print('------------------')
a=a-np.mean(a,axis=1)
print(a)
print('------------------')
b=np.square(a)
print(b)
print('------------------')
flat = a.flatten()
indices = np.argpartition(flat, -3)[-3:]
row, col = np.unravel_index(indices, a.shape)
print("Indices of top 3 maximum values:")
for i in range(3):
    print(f"Value: {a[row[i]][col[i]]}, Index: ({row[i]}, {col[i]})")

[[ 2  8 19]
 [17  7 10]
 [10  9 14]]
------------------
[[-7.66666667 -3.33333333  8.        ]
 [ 7.33333333 -4.33333333 -1.        ]
 [ 0.33333333 -2.33333333  3.        ]]
------------------
[[58.77777778 11.11111111 64.        ]
 [53.77777778 18.77777778  1.        ]
 [ 0.11111111  5.44444444  9.        ]]
------------------
Indices of top 3 maximum values:
Value: 3.0, Index: (2, 2)
Value: 7.333333333333334, Index: (1, 0)
Value: 8.0, Index: (0, 2)
