<a href="https://colab.research.google.com/github/kundetigowtham06/ML/blob/main/mlproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a="Gowtham"

In [ ]:
print(a)

Gowtham


In [ ]:
def prime(n):
  for i in range(2,n):
    if n%i==0:
      return "not a prime"
  return("prime")
print(prime(4))

not a prime


In [ ]:
!python --version

Python 3.10.12


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3]) # rank 1
print(type(a),a.shape,a)
a[0]=6
print(a)


<class 'numpy.ndarray'> (3,) [1 2 3]
[6 2 3]


In [ ]:
b=np.array([[1,23,34],[45,6,8]]) #rank 2
print(b)
print(b.shape)

[[ 1 23 34]
 [45  6  8]]
(2, 3)


#important functions

In [ ]:
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(c[0,0])

0.0


In [ ]:
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
